export const Strings = {
    API: {
        BASE_URL: 'https://www.mocky.io',
        V2: '/v2',
        PRODUCTS_ENDPOINT: '/5c3e15e63500006e003e9795',
    },
    EN: {
        'Our_Products': 'Our Products',
        'Products': 'Products',
        'Products_Subtitle': 'Take a look at our products. Click to see more, swipe to do more.',
        'Add': 'Add',
        'Update': 'Update',
        'Overview': 'Overview',
        'Overview_Subtitle': 'View the price history and other details of this product.',
        'No data': 'No data',
        'Add_Product': 'Add Product',
        'Add_Product_Subtitle': 'Add a new product to the list.',
        'Add_Price': 'Add Price',
        'Add_Price_Subtitle': 'Set a new price for',
        'Update_Product': 'Update Product',
        'Update_Product_Subtitle': 'Update the details of this product.',
        'Product_Name': 'Product Name',
        'Product_Name_Subtitle': 'Enter the name of the product.',
        'Product_Price': 'Product Price',
        'Product_Price_Subtitle': 'Enter the price of the product.',
        'Price_Date': 'Price Date',
        'Price_Date_Subtitle': 'Enter the date of the price.',
        'Enter_a_valid_name': 'Enter a valid name.',
        'Enter_a_valid_price': 'Enter a valid price.',
        'New_price': 'New price',
        'Reset_data': 'Reset data',
        'Price': 'Price',
        'Date_created': 'Date created',
        'Percentage_change': 'Percentage change',
        'N_A': 'N/A',
        'Toggle_theme': 'Toggle theme',
        'Screen_not_available': 'Screen not available',
        'Go_to_home': 'Go to home',
    },
    STORAGE_KEYS: {
        'Products_key': '_Products_key_',
    },
}